# Generated by Django 5.0.4 on 2024-07-31 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_match_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_match', to='main_app.tennisplayer'),
        ),
    ]
