# Generated by Django 5.0.4 on 2024-07-31 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_match_score_alter_match_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='players',
            field=models.ManyToManyField(related_name='players', to='main_app.tennisplayer'),
        ),
    ]
