# Generated by Django 5.0.7 on 2024-07-24 19:06

from django.db import migrations


class Migration(migrations.Migration):

    def connect_the_relationships(apps, schema_editor):
        Fruit_model = apps.get_model('fruits', 'Fruit')

        query = Fruit_model.objects.filter(name__exact='Banana').update(
            category=2
        )

    def reverse_connections(apps, schema_editor):
        Fruit_model = apps.get_model('fruits', 'Fruit')
        query = Fruit_model.objects.exclude(category__id=1).update(
            category=1
        )


    dependencies = [
        ('fruits', '0002_fruit_category'),
    ]

    operations = [
        migrations.RunPython(connect_the_relationships,reverse_code=reverse_connections)
    ]
