# Generated by Django 5.0.4 on 2024-06-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_person_age_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age_group',
            field=models.CharField(blank=True, default='No age group', max_length=20, null=True),
        ),
    ]
