# Generated by Django 5.0.4 on 2024-06-27 08:46

from django.db import migrations


class Migration(migrations.Migration):

    def define_age_group(apps, schema_editor):
        person_model = apps.get_model('main_app', 'Person')

        people = person_model.objects.all()

        for curr_person in people:
            if curr_person.age <= 12:
                curr_person.age_group = 'Child'
            elif curr_person.age <= 17:
                curr_person.age_group = "Teen"
            else:
                curr_person.age_group = "Adult"

        person_model.objects.bulk_update(people, ['age_group'])

    def reverse_age_group(apps, schema_editor):
        person_model = apps.get_model('main_app', 'Person')
        people = person_model.objects.all()

        for curr_person in people:
            curr_person.age_group = person_model._meta.get_field('age_group').default

        person_model.objects.bulk_update(people, ['age_group'])

    dependencies = [
        ('main_app', '0013_alter_person_age_group'),
    ]

    operations = [
        migrations.RunPython(define_age_group, reverse_code=reverse_age_group)
    ]
