# Generated by Django 5.0.4 on 2024-06-27 14:30

from django.db import migrations


class Migration(migrations.Migration):

    def define_rarity_from_price(apps, schema_editor):
        item = apps.get_model('main_app', 'Item')
        item_objects = item.objects.all()

        for cur_item in item_objects:
            if cur_item.price <= 10:
                cur_item.rarity = 'Rare'

            elif cur_item.price <= 20:
                cur_item.rarity = 'Very Rare'

            elif cur_item.price <= 30:
                cur_item.rarity = 'Extremely Rare'

            else:
                cur_item.rarity = 'Mega Rare'

        item.objects.bulk_update(item_objects, ['rarity'])


    def reverse_rarity(apps, schema_editor):
        item = apps.get_model('main_app', 'Item')
        item_objects = item.objects.all()

        for cur_item in item_objects:
            cur_item.rarity = item._meta.get_field('rarity').default

        item.objects.bulk_update(item_objects, ['rarity'])

    dependencies = [
        ('main_app', '0015_item'),
    ]

    operations = [
        migrations.RunPython(define_rarity_from_price, reverse_code=reverse_rarity)
    ]
