# Generated by Django 5.0.4 on 2024-06-27 14:46

from django.db import migrations


def set_price(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    all_phones = smartphone.objects.all()

    for phone in all_phones:
        phone.price = len(phone.brand) * 120

    smartphone.objects.bulk_update(all_phones, ['price'])


def set_category(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    all_phones = smartphone.objects.all()

    for phone in all_phones:
        if phone.price >= 750:
            phone.category = 'Expensive'
        else:
            phone.category = 'Cheap'

    smartphone.objects.bulk_update(all_phones, ['category'])


def reverse_columns(apps, schema_editor):
    smartphone = apps.get_model('main_app', 'Smartphone')
    all_phones = smartphone.objects.all()

    for phone in all_phones:
        phone.category = smartphone._meta.get_field('category').default
        phone.price = smartphone._meta.get_field('price').default

    smartphone.objects.bulk_update(all_phones, ['category', 'price'])


def set_all_columns(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_smartphone'),
    ]

    operations = [
        migrations.RunPython(set_all_columns, reverse_code=reverse_columns)
    ]
