# Generated by Django 5.0.4 on 2024-06-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_alter_order_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='warranty',
            field=models.CharField(default='No warranty'),
        ),
    ]
