# Generated by Django 5.0.4 on 2024-06-27 15:09

from django.db import migrations
from django.utils import timezone

def set_order_information(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    all_orders = order_model.objects.all()

    for order in all_orders:
        if order.status == 'PD':
            order.delivery = order.order_date + timezone.timedelta(days=3)
            order.save()

        elif order.status == 'CP':
            order.warranty = '24 months'
            order.save()

        elif order.status == 'CA':
            order.delete()


def reverse_delivery_update_on_information(apps, schema_editor):
    order_model = apps.get_model('main_app', 'Order')
    all_order = order_model.objects.all()

    for order in all_order:
        if order.status == 'PD':
            order.delivery = None

        elif order.status == 'CP':
            order.warranty = order_model._meta.get_field('warranty').default

        order.save()


class Migration(migrations.Migration):
    dependencies = [
        ('main_app', '0021_alter_order_warranty'),
    ]

    operations = [
        migrations.RunPython(set_order_information, reverse_code=reverse_delivery_update_on_information)
    ]

