# Generated by Django 5.0.4 on 2024-07-23 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_movie_starring_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='birth_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_date',
            field=models.DateField(default=datetime.date(1900, 1, 1)),
        ),
    ]
