# Generated by Django 5.0.4 on 2024-07-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_actor_birth_date_alter_director_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='storyline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
