# Generated by Django 5.0.4 on 2024-07-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_movie_storyline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='last_update',
            new_name='last_updated',
        ),
    ]
