# Generated by Django 5.0.4 on 2024-07-23 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_movie_actors_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='starring_actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movies_main_role', to='main_app.actor'),
        ),
    ]
