# Generated by Django 5.0.4 on 2024-06-21 22:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('main_app', '0001_initial'), ('main_app', '0002_product_created_at_product_last_edited_on'), ('main_app', '0003_product_count'), ('main_app', '0004_alter_product_category_alter_product_supplier')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=100, null=True)),
                ('supplier', models.CharField(max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 21, 21, 38, 20, 222713, tzinfo=datetime.timezone.utc))),
                ('last_edited_on', models.DateTimeField(auto_now=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
