# Generated by Django 5.0.4 on 2024-06-28 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='populate',
            new_name='population',
        ),
    ]
