# Generated by Django 5.0.4 on 2024-06-19 15:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_gender_alter_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='childrens',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=800, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
