# Generated by Django 5.0.6 on 2024-06-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_delete_employee_remove_user_childrens_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('VR', 'Varna'), ('BS', 'Burgas'), ('PL', 'Plovdiv'), ('SF', 'Sofia')], default='Sofia', max_length=30),
        ),
    ]
