# Generated by Django 5.0.6 on 2024-06-21 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_city_remove_user_number_user_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='children',
        ),
    ]
