# Generated by Django 5.0.4 on 2024-06-21 22:26

from django.db import migrations


class Migration(migrations.Migration):

    def reverse_names(apps, schema_editor):
        Users = apps.get_model('users', 'User')
        for user in Users.objects.all():
            if user.gender in('Male', 'Female'):
                user.name = user.name[4:]
                user.save()

    def process_names(apps, schema_editor):
        Users = apps.get_model('users', 'User')

        for user in Users.objects.all():
            if user.gender == 'Male':
                user.name = f'Mr. {user.name}'

            user.save()

    dependencies = [
        ('users', '0005_remove_user_children'),
    ]

    operations = [
        migrations.RunPython(process_names, reverse_code=reverse_names)
    ]
