# Generated by Django 5.0.4 on 2024-06-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('Sofia', 'Sofia'), ('Plovidv', 'Plovidv'), ('Varna', 'Varna'), ('Burgas', 'Burgas')], max_length=20, null=True),
        ),
    ]
