# Generated by Django 5.0.4 on 2024-06-19 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_department_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(choices=[('VR', 'VARNA'), ('BS', 'Burgas'), ('PV', 'Plovdiv'), ('SF', 'Sofia')], default='Varna', max_length=20, null=True),
        ),
    ]
