# Generated by Django 5.0.4 on 2024-07-05 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_license_drivinglicense'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='License',
            new_name='Driver',
        ),
    ]
